services:
  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    ports:
      - "$PORT:$PORT"
    expose:
      - "$PORT"
    volumes:
      - .:/build_/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
